Delete http://localhost:3000/adoption-applications/6658934853153ca12e54a22b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6IjY2NTZjN2I1MjRkODU0NTExYWMzOTA3YiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNzE0MjA4MSwiZXhwIjoxNzE3MTQ1NjgxfQ.9LGR7YKdRQO9oVDyJc39ZukHcwv8i5eAYuWZTc1hmyY
